global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'openeuler-host'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'openEuler-24.03-LTS'
