# ========================================================
# 全局 80 端口 HTTP -> 自动 301 强制跳转 HTTPS
# ========================================================
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}
