-- 1. 锁等待关系与死锁阻塞源头深度排查
SELECT 
    W.ID AS 等待事务ID,
    W.WAIT_FOR_ID AS 阻塞源头事务ID,
    W.WAIT_TIME AS 等待耗时_ms,
    S1.SESS_ID AS 被阻塞会话ID,
    S1.SQL_TEXT AS 被阻塞SQL,
    S2.SESS_ID AS 源头会话ID_该杀,
    S2.USER_NAME AS 源头用户名,
    S2.CLNT_IP AS 源头客户端IP,
    S2.SQL_TEXT AS 源头SQL
FROM V$TRXWAIT W
LEFT JOIN V$SESSIONS S1 ON W.ID = S1.TRX_ID
LEFT JOIN V$SESSIONS S2 ON W.WAIT_FOR_ID = S2.TRX_ID;

-- 2. 强制杀死阻塞源头会话
-- CALL SP_CLOSE_SESSION(源头会话ID);

-- 3. 表空间综合容量与聚合使用率巡检
SELECT 
    TS.NAME AS 表空间名,
    COUNT(DF.PATH) AS 包含数据文件数,
    ROUND(SUM(DF.TOTAL_SIZE) * PAGE / 1024 / 1024.0, 2) AS 表空间总容量_MB,
    ROUND(SUM(DF.FREE_SIZE) * PAGE / 1024 / 1024.0, 2) AS 表空间剩余总空间_MB,
    ROUND((SUM(DF.TOTAL_SIZE) - SUM(DF.FREE_SIZE)) * PAGE / 1024 / 1024.0, 2) AS 已用总空间_MB,
    ROUND((SUM(DF.TOTAL_SIZE) - SUM(DF.FREE_SIZE)) * 100.0 / SUM(DF.TOTAL_SIZE), 2) AS "表空间综合使用率_%"
FROM V$TABLESPACE TS
JOIN V$DATAFILE DF ON TS.ID = DF.GROUP_ID
GROUP BY TS.NAME
ORDER BY "表空间综合使用率_%" DESC;

-- 4. 在线动态扩容表空间
-- ALTER TABLESPACE MAIN ADD DATAFILE '/dmdata/data/DAMENG/MAIN_02.DBF' SIZE 64 AUTOEXTEND ON NEXT 32 MAXSIZE 2048;
